---
name: docker-image
run-name: ${{ github.actor }} pushed "${{ github.event.head_commit.message }}" to ${{ github.ref_name }}
on:
  push:
    branches: [master]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build, tag, and push docker image to ECR
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/broadstripes/prj2epsg:latest
        platforms: linux/amd64,linux/arm64
        provenance: false
    - name: Alert Slack
      if: failure()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: |
          {
            "buildType":"Prj2EPSG image build",
            "githubUsername":"${{ github.actor }}",
            "buildResultURL":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FAIL_WORKFLOW_WEBHOOK_URL }}
